############################
## BUILD
############################
FROM python:3.10-slim as builder

# Copy in app src code
COPY requirements.txt /app/requirements.txt

COPY ./src /app

############################
## RELEASE
############################
FROM scratch as release

# Set path
ENV PATH=/usr/local/bin:$PATH

# Pull in shell binary
COPY --from=builder /bin/sh /bin/sh
COPY --from=builder /bin/ls /bin/ls

RUN ls /bin

# Pull python resources in from build stage
COPY --from=builder /usr/local /usr/local

# Set the working directory
WORKDIR /app

# Copy in the app source code from build stage
COPY --from=builder /app /app

# Install python dependencies
RUN python -m pip install --no-cache-dir -r requirements.txt

# Expose the service port
EXPOSE 8000

# Run the service
CMD ["python","src/app.py","--service-address","0.0.0.0","--service-port","8080"]