environment: dev
domain: grove.sirwac.net
system: challenge
serviceName: api

replicaCount: 1

image:
  repository: grover424/challenge-api
  pullPolicy: Always
  tag: latest

containerPorts:
  - 8000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
    traefik.ingress.kubernetes.io/router.middlewares: challenge-api-ssl-redirect@kubernetescrd
  hosts:
    - host: challenge-api.grove.sirwac.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: certificate-api
      hosts:
        - challenge-api.grove.sirwac.net
  certificate:
    environment: production
    duration: 2160h
    renewalLeadTime: 360h
    organization: Grove
